matrix.o: matrix.c matrix.h
mmu_manager.o: mmu_manager.c mmu_manager.h include/hardware.h swap.c \
 hw_config.h swap.h
oracle.o: oracle.c hw_config.h matrix.h
swap.o: swap.c include/hardware.h hw_config.h swap.h
user_process.o: user_process.c hw_config.h matrix.h
